### ISSUE TITLE
[website_seo] Language change in frontend leads to 404 page with new seo urls

### ISSUE THREAD

**Issue by rruebner** [blooparksystems/website#10]
# Problem

If you create a new page and add a seo url in at least two languages the language change on this page won't work. You will get a 404 error.
# Steps to reproduce
- install a second language
- create a new page or use an existing page
- add a seo url for english and your new installed language (seo url's should differ, e. g. "contact" and "kontakt")
- open this page in the frontend
- change the language -> you get a 404 error

We have to update the change language function for the seo urls to solve this problem.

**Comment by kaerdsar** [comment]
This problem also appears with blog and blog post pages. We have to update the url_for_lang method to cover website_blog seo urls.
