### ISSUE TITLE
change generation for url language code from en_US to en

### ISSUE THREAD

**Issue by jholze** [blooparksystems/website#13]
### current behavior

The language code used in the urls is like en_US, de_DE etc. I found a blog post https://myodoo.de/de/blog/neuigkeiten-1/post/seo-optimierungen-fur-odoo-8-26 which also changes the behavior. We should discuss if we need to add a new field or if we can use the iso code, which is still used to generate the hreflang attribute eg. 

`<link rel="alternate" hreflang="en" href="http://bloopark.de/en_US/">`

Examples

domain.com/de_DE/page/....
### expected behavior

For a better SEO behavior it should be simple en, de etc.

Example

domain.com/de/page/...

But pay attention to this https://github.com/odoo/odoo/pull/3965 because they tried also to use another language code and failed.
### helpful links

https://support.google.com/webmasters/answer/189077?hl=en

**Comment by kaerdsar** [comment]
I read the conversation in https://github.com/odoo/odoo/pull/3965 and tested the proposal from @88kbbq but with a little difference. I didn't add a new field for url_code, I used the iso_code field. According to this https://support.google.com/webmasters/answer/189077?hl=en, the iso_code is a valid code for url.

Then I tried to check about @mart-e warning: "If you change the url code, you lose every existing translation (not matching the code) and you can not add new terms (no matching with known languages)."

He was right, some existing translation does not work. Then I tried to use the iso_code like an alias and  keep using the original lang code. The target was find the points in source code where the lang code it's used to consult or write in database and there convert iso_code to code.

I added a commit with a solution (https://github.com/kaerdsar/website/commit/783bd12f0443480623214b5aa477f51ad4e04f1a). According to my tests the translations works fine. I would need some help to test and see if it is a valid solution.

**Comment by 88kbbq** [comment]
Google does not recommend underscored in URLs.
https://support.google.com/webmasters/answer/76329?hl=en
This value should be completely customizable, not set to a iso or locale
code. Remember, this isn't the 00's; Odoo needs current shop owner to
migrate platforms. Most businesses now either have a facebook, spotify,
wordpress, or magento site, and a new comer needs to be better, or at least
compatible with, the rest of the pack. I tried to help, but the
investigation led back the the Odoo team. It's going to take a lot to fit
the URL issue, but until that's fixed there won't be any mass migration. We
need a seamless avenue to move without the risk of losing our hard earned
SERP rankings.

**Comment by kaerdsar** [comment]
Thanks for your post. Right, iso_code also uses underscore. We can add the new field you used before. Anyway the solution can be applied with our website_seo module. In this solution we don't need mass migration, the module converts url_code to code just before using for database. The existing translation will work too. What do you think?

I'm going to restore the url_code field in next commit.

**Comment by jholze** [comment]
Hey, i think a new field eg. short_code or url_code will be better. @88kbbq you are right. Our plan is to discuss all of our changes with the odoo team, because SEO improvements are really needed in odoo 8 and 9.

**Comment by 88kbbq** [comment]
Very excited to see movement on Odoo CMS SEO. Hopefully this functionality will extend into modules like blog, e-commerce, forum, events, etc. It is the single point of failure in our migration plan. For multilingual sites, a subdomain/subfolder option should exist. I've installed v9 and see some great improvements; very hopeful for a 2016 migration.
