### ISSUE TITLE
improve SEO Handling for html lang

### ISSUE THREAD

**Issue by fczaja** [blooparksystems/website#18]
## Description

The HTML lang attribute should be changeable by the shop owner, so he can use the language-country notation (e.g. en-US) or the language notation (e.g. en) per language.
### Reason

Google decides by the HTML lang attribute where in the world the contents of the website are found in the Google search.
## current behavior

For example the default HTML lang attribute for english pages is currently

```
<html lang="en-us">
```

Here we are only relevant for the english language in the United States.
## expected behavior

We need a selection box in the odoo backend where we can change the HTML lang per language. It must be possible to select

```
<html lang="en">
<html lang="en-US">
<html lang="de">
<html lang="de-DE">
etc.
```

If a selection box is to complicated a simple char field per language is also acceptable. Than the shop owner has to fill in the correct language-country or language notation.

**Comment by kaerdsar** [comment]
In the current solution there is a new field for model res.lang (language) named short_code. You can access in the systems by Settings / Translations / Language. This field is used to improve SEO URL, there is a closed issue related: https://github.com/blooparksystems/website/issues/13.

When you set short_code with "en" then HTML lang also use that value. Then you can decide what HTML lang to use editing short_code for each language.

My question:  is that enough? or do we need one variables for URL lang and another variable for HTML lang?

**Comment by jholze** [comment]
:+1:  the current implemented solution is fine for me. I think we need to have the runbot running, because it will be easier for testing. Would be also nice to have a link to the related build in a ticket like in jira / bamboo
