### ISSUE TITLE
Note Field - Meta Description & Title

### ISSUE THREAD

**Issue by fczaja** [blooparksystems/website#19]
## Description

We need two information fields next to the input fields for the title tag and the meta description to show a declaration of the two elements in the frontend promote panel.
### Reason

We want to explain the two SEO features to inexperienced users because they can't make a good SEO work without useful information.
## current behavior

There is currently no explanation to see.
## expected behavior

The two information fields for the title tag and meta description should be available by default.
## Display the note field

Right next to the fields could be a small question mark or Help. When you click a window opens showing the information.
## Contents of the note fields

Title-tag

German
Der Title Tag bezieht sich auf das Thema der HTML Seite. Es ist für Google sehr wichtig und sollte den Seiteninhalt sehr gut beschreiben.
Der Title Tag wird in den Google Suchergebnisseiten angezeigt.
Der Title Tag sollte maximal 55 Zeichen (mit Leerzeichen) lang sein. Zur Not kann es auch ein wenig länger sein, es wird dann in den Suchergebnissen abgeschnitten.
Das Schlüsselwort sollte wenn möglich vorn stehen.

English
The title tag refers to the topic of the HTML page. It is very important for Google and should describe the content very well.
The title tag is displayed in the Google search results pages.
The title tag should have a maximum of 55 characters (including spaces). It can also have more characters, it will be cut in the search results.
If possible the keyword should be at the beginning.

Meta-Description

German
Die Meta Beschreibung wird auf den Google Suchergebnisseiten angezeigt.
Die Meta Beschreibung ist eine nähere Charakterisierung der HTML Seite. Sie soll Benutzer animieren auf das Suchergebnis zu klicken (Call-to-Action).
Die Länge sollte maximal 156 Zeichen (mit Leerzeichen) betragen.

English
The meta description will be displayed on the Google search results pages.
The meta description is a detailed characterization of the HTML page. It should encourage users to click on the search result (Call-to-Action).
The length should be a maximum of 156 characters (including spaces).

**Comment by rruebner** [comment]
@kaerdsar So far so good. Please update the english notes in the data files, I updated the texts in the issue description. In addition provide the german translation too.

**Comment by rruebner** [comment]
Review was fine :+1:. If the related pull request is created it will be merged.
