### ISSUE TITLE
Avoid editing of the SEO Field on website homepage

### ISSUE THREAD

**Issue by fczaja** [blooparksystems/website#22]
## SEO URL field must be removed from the Home page

Impacted versions:
- 9.0
### Goal

The home page has no URL, so the "SEO URL" Promote / Optimize SEO field should be hidden or not rendered. Should be also work for multi websites in one DB - should be tested
### Current behavior:

Currently, the "SEO URL field" on the home page can be seen and it can be a URL are entered. Plotting a URL to the home page is redirected to the new URL and Promote panel no longer works.
### Expected Behavior:

The "SEO URL field" i Promote / Optimize SEO field will be removed so that there are no changes can be made.

**Comment by rruebner** [comment]
If #25, #26 and #27 are finished I will do the review.

**Comment by rruebner** [comment]
@kaerdsar Your solution works for "/" but not for the default odoo homepage route "/page/homepage/".
I don't know if there is a better solution than to exclude simply "/page/homepage/" next to "/". Maybe you can use the key field "website.hompage" of the ir.ui.view record in some way.

**Comment by kaerdsar** [comment]
@rruebner now it also works with '/page/homepage', you can see it in the commit https://github.com/blooparksystems/website/commit/34e271a66a1ae9d3aeb7a890b553341fe9089859

**Comment by rruebner** [comment]
Review was fine :+1:. Code changes were already merged.
