### ISSUE TITLE
update google like link preview with new SEO url value

### ISSUE THREAD

**Issue by fczaja** [blooparksystems/website#23]
Impacted versions:
  - 9.0
## goal

In Promote panel below the SEO field of point 3 "Preview" is here the new URL should change according to the URL will be displayed.
### Steps to Reproduce:

Go to Promote / Optimize SEO
Give a new URL in the "SEO URL box" a
Now under point 3 "Preview" the old URL
### Current behavior:

Currently the URL is not updating in the google like preview section, when a user enters a custom CEO URl. The Odoo default url is shown
### Expected Behavior:

If you enter a new URL in the "SEO URL" Point 3 "Preview", the preview should change

**Comment by kaerdsar** [comment]
The google preview link works fine now. I made some update to can edit SEO variables in alternate languages in the same Promote Panel window.

I have a question:
Our default language is German and English is the other language. If we edit seo_url field for English version and set 'service_seo_en', google preview link shows this: http//localhost:8069/service_seo_en. But the correct URL is: http//localhost:8069/en/service_seo_en.

I'm afraid google preview link must show the second one like we use it in tag <link rel="alternate" ... >. Is this correct?

**Comment by jholze** [comment]
Hi Cesar, just to clarify

we can currently run domain.com/company  (which is en) and domain.com/unternehmen (which is de) with the SEO Suite ? or do we have the link without the language code just for the default website language ? Normally further languages should have the short code like /en/....url...like you did in #13 - so the google preview should also contain the language short code, but not if the default language is set

**Comment by kaerdsar** [comment]
We have the link without the language code just for the default website language. Your example works in this way (default language de):
- domain.com/en/company
- domain.com/unternehmen

**Comment by jholze** [comment]
:+1:
