### ISSUE TITLE
Change parent for menu related to a view with seo_url doesn't work.

### ISSUE THREAD

**Issue by kaerdsar** [blooparksystems/website#31]
Impacted versions:
- 9.0
## Goal

Each time a menu it's moved from parent the related url and view seo_url must be updated.
### Current Behavior 1:

When you change the menu parent of a menu related to a view with seo_url get 404 error. Later go for Homepage and go to the link of the menu and it works, but translation is not updated.

Steps to Reproduce:

Go to Content / New Page (eg: Products)
Go to Promote / Optimize SEO and set seo_url for the page (products_seo)
Go to Content / New Page (eg: Laptops)
Go to Promote / Optimize SEO and set seo_url for the page (laptops_seo)
Go to Content / Edit Menu and move Laptops menu under Products menu
Save Edit menu dialog
Here appears a 404 page
### Expected Behavior:

When you move a menu (related to a view with seo_url) under other menu (also related to a view with seo_url) the page must be redirected updated. The views and menus must update URL ans seo_url.

**Comment by rruebner** [comment]
Review was fine :+1:
