### ISSUE TITLE
fix some labels in SEO panel and add sublabels

### ISSUE THREAD

**Issue by jholze** [blooparksystems/website#44]
- some labels (see attached screenshot should be changes for german language)
- also add some sublabels to show the real html tag value eg. description could be like meta name="Description"  because if someone has the knowledge its more useful instead of simple labels

![seo_panel_fix_labels](https://cloud.githubusercontent.com/assets/6851586/11241693/2f8a002e-8dfd-11e5-8d45-7a6a8a31d7b8.png)

**Comment by kaerdsar** [comment]
Solved with pull request 47 and 48.
