### ISSUE TITLE
Meta and robots information won't be saved in promote panel on home page

### ISSUE THREAD

**Issue by rruebner** [blooparksystems/website#56]
# Problem

If you try to change meta or robots information in the promote panel on the home page you will get a SEO url validation error.
# Steps to reproduce
- create a new database with language german and with demo data
- install the website_seo module
- activate the developer mode
- go to Settings -> Translations -> Languages and set the "Short code" to "en" for the "English" entry
- go to Website Admin -> Configuration and add "German / Deutsch" as second language ans as default language and save
- go to the home page in the frontend, open the promote panel, change the meta title or meta description or robots content and save: you will get the error "Invalid SEO URL. The allowed characters are a-z, A-Z, 0-9, - and _." and nothing will be saved
# Expected behaviour
- the meta title, meta description and robots content should also be changeable in the promote panel on the home page

**Comment by ghost** [comment]
Merged PR #59
