### ISSUE TITLE
[website_seo] Add SEO url level and parent changes when adding / updating the menu entries in the frontend and backend

### ISSUE THREAD

**Issue by rruebner** [blooparksystems/website#6]
# Goal

If you add or update the odoo menu in the backend and frontend you can also move menu entries. Means you can create a hierarchical menu entries. This hierarchy updates should also be applied to our seo_parent and seo_url_level fields
## ToDo
- update the website_seo module and provide a PR for the branch 8.0-wip-website-seo
- update seo_parent and seo_url_level of the related view when updating menu entries in the frontend
- update seo_parent and seo_url_level of the related view when updating menu entries in the backend

**Comment by rruebner** [comment]
:thumbsup: code looks fine, I will merge it at the weekend

**Comment by rruebner** [comment]
@kaerdsar After some additional testing I run into some troubles
- if you create a new page via the frontend menu the seo data isn't added correctly (e. g. the seo_url_level is -1)
- if I drag&drop a menu entry via the frontend menu the menu url is not updated

**Comment by kaerdsar** [comment]
@rruebner I only update menu url if the corresponding view has seo_url setted. Maybe we also can add a default seo_url for new views.

**Comment by rruebner** [comment]
@kaerdsar The troubles are gone :) but the seo_url_level of the view still isn't changing when I drag&drop a menu entry via the frontend menu. And the menu url still isn't updated too (see my other comment in the commit https://github.com/kaerdsar/website/commit/5bccec595eb2971474ae3345cae93926b8d57e51)
