### ISSUE TITLE
[website_seo] Managing of the SEO Urls should be completely possible in the promote panel

### ISSUE THREAD

**Issue by kaerdsar** [blooparksystems/website#7]
# Goal

The website_seo module adds the field seo_url to website.seo.metadata model. When you click on Promote (in Website Builder) and see the 'Promote this Page' window you should be able to edit the field seo_url value. Something similar to field website_meta_robots from website.seo.metadata model must be done.
# ToDo
- Inherit template view website.seo_configuration and add the field
- Check javascript to ensure the form save and read field value properly

**Comment by jholze** [comment]
@rruebner would be nice if you could add german translations for each ticket. Thanks

**Comment by jholze** [comment]
:+1:

**Comment by rruebner** [comment]
:thumbsup: code looks fine, I will merge it at the weekend
